import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Snowflakes from '@/components/Snowflakes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-blue-950 overflow-hidden h-full">
      <body className={`${inter.className}`}>
        <Snowflakes />
        {children}
      </body>
    </html>
  )
}
